Add Php 8.0 support, bump minimum php 7 to 7.4, update other necessar…
Speicher210/business-hours pull request #2
Opened 2021-11-05 09:43 UTC by evang522

…y dependencies

Resolves #1   

@dragosprotung   just two questions: 

- is the versioning I put in the Changelog Right?

- The newer version of PHPstan which was required in order to update to PHP 8 finds many more errors. I generated a baseline / config file in the dev env, but haven't included it in this commit as I'm not sure how many changes I should bring into the branch. Just let me know and I should add it.   

Thanks :)

2021-11-05 12:11 UTC, dragosprotung requested changes
Let's run the build first so I can see how big the baseline is

2021-11-05 12:11 UTC, dragosprotung commented on .github/workflows/build.yml
> +    branches: [ master ]
Only for the `2.0` branch

2021-11-05 12:11 UTC, dragosprotung commented on .github/workflows/build.yml
> +    branches: [ master ]
Only for the `2.0` branch

2021-11-05 12:11 UTC, dragosprotung commented on CHANGELOG.md
> +## [2.1.0] - 2021-11-05
Do not specify the date yet, simply set it to `2021-XX-XX`

2021-11-05 12:13 UTC, dragosprotung commented on .github/workflows/build.yml
> +        run: composer check
You will need to add this to composer script in order to run all the checks. See `master` for example

2021-11-05 19:30 UTC, dragosprotung requested changes
I think is OK to create a baseline file and ignore the errors

2021-11-06 10:05 UTC, evang522 commented
@dragosprotung  
I added the baseline file now, but it has 85 errors in it because of the tests.  

Since in the composer phpstan script the level was different for `tests` (4)  and `src` (6), the tests emitted more errors when set to level 6. Since you can't specify separate levels for different paths in the config, according to https://github.com/phpstan/phpstan/issues/3640 the recommendation is to use the baseline to make this differentiation instead. 

Let me know if I should change it to simply using the separate cli commands though.

2021-11-06 12:32 UTC, merged